name: 书旗小说


on:
  workflow_dispatch:
  schedule:
     - cron: '1 */6 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
  
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【书旗】'
        if: env.shuqiuserurlVal
        run: |
          node Task/shuqi.js
         env:
          shuqiuserurlVal: ${{ secrets.shuqiuserurlVal }}
          shuqisyurlVal: ${{ secrets.shuqisyurlVal }}
          shuqisybodyVal: ${{ secrets.shuqisybodyVal }}
          shuqispbodyVal: ${{ secrets.shuqispbodyVal }}
          shuqiscbodyVal: ${{ secrets.shuqiscbodyVal }}
          shuqiydbodyVal: ${{ secrets.shuqiydbodyVal }}
          shuqiqdbodyVal: ${{ secrets.shuqiqdbodyVal }}
          shuqirwbodyVal: ${{ secrets.shuqirwbodyVal }}
          shuqifxbodyVal: ${{ secrets.shuqifxbodyVal }}
          shuqisprwurlVal: ${{ secrets.shuqisprwurlVal }}
          shuqijlbodyVal: ${{ secrets.shuqijlbodyVal }}
          shuqisqjlbodyVal: ${{ secrets.shuqisqjlbodyVal }}
          shuqicjyurlVal: ${{ secrets.shuqicjyurlVal }}
          shuqicjcsbodyVal: ${{ secrets.shuqicjcsbodyVal }}
          shuqicjbodyVal: ${{ secrets.shuqicjbodyVal }}
          
          
          shuqijsspbodyVal: ${{ secrets.shuqijsspbodyVal }}
          shuqijsydurlVal: ${{ secrets.shuqijsydurlVal }}
          shuqijsydbodyVal: ${{ secrets.shuqijsydbodyVal }}
          shuqijsqdbodyVal: ${{ secrets.shuqijsqdbodyVal }}
          shuqijsqdspyurlVal: ${{ secrets.shuqijsqdspyurlVal }}
          shuqijsqdspbodyVal: ${{ secrets.shuqijsqdspbodyVal }}
          shuqijsrwbodyVal: ${{ secrets.shuqijsrwbodyVal }}
          shuqijsfxbodyVal: ${{ secrets.shuqijsfxbodyVal }}
          shuqijsbookurlVal: ${{ secrets.shuqijsbookurlVal }}
          shuqijsbookbodyVal: ${{ secrets.shuqijsbookbodyVal }}
          shuqijssprwurlVal: ${{ secrets.shuqijssprwurlVal }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
